[2024-11-28T11:13:16.790+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: challenge_dag.extract_task manual__2024-11-28T11:13:14.192164+00:00 [queued]>
[2024-11-28T11:13:16.795+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: challenge_dag.extract_task manual__2024-11-28T11:13:14.192164+00:00 [queued]>
[2024-11-28T11:13:16.796+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-11-28T11:13:16.812+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): extract_task> on 2024-11-28 11:13:14.192164+00:00
[2024-11-28T11:13:16.818+0000] {standard_task_runner.py:57} INFO - Started process 49227 to run task
[2024-11-28T11:13:16.824+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'challenge_dag', 'extract_task', 'manual__2024-11-28T11:13:14.192164+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/challenge_dag.py', '--cfg-path', '/tmp/tmpkh06c_8i']
[2024-11-28T11:13:16.824+0000] {standard_task_runner.py:85} INFO - Job 12: Subtask extract_task
[2024-11-28T11:13:16.855+0000] {task_command.py:410} INFO - Running <TaskInstance: challenge_dag.extract_task manual__2024-11-28T11:13:14.192164+00:00 [running]> on host codespaces-c5d7e2
[2024-11-28T11:13:16.892+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='challenge_dag' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-28T11:13:14.192164+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-28T11:13:14.192164+00:00'
[2024-11-28T11:13:16.893+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-28T11:13:16.893+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'wget -c https://raw.githubusercontent.com/LinkedInLearning/hands-on-introduction-data-engineering-4395021/main/data/constituents.csv -O /workspaces/hands-on-introduction-data-engineering-4395021/lab/challenge/challenge-extract-data.csv']
[2024-11-28T11:13:16.902+0000] {subprocess.py:86} INFO - Output:
[2024-11-28T11:13:16.907+0000] {subprocess.py:93} INFO - --2024-11-28 11:13:16--  https://raw.githubusercontent.com/LinkedInLearning/hands-on-introduction-data-engineering-4395021/main/data/constituents.csv
[2024-11-28T11:13:16.916+0000] {subprocess.py:93} INFO - Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.110.133, ...
[2024-11-28T11:13:16.924+0000] {subprocess.py:93} INFO - Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
[2024-11-28T11:13:16.952+0000] {subprocess.py:93} INFO - HTTP request sent, awaiting response... 416 Range Not Satisfiable
[2024-11-28T11:13:16.952+0000] {subprocess.py:93} INFO - 
[2024-11-28T11:13:16.952+0000] {subprocess.py:93} INFO -     The file is already fully retrieved; nothing to do.
[2024-11-28T11:13:16.953+0000] {subprocess.py:93} INFO - 
[2024-11-28T11:13:16.953+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-11-28T11:13:16.966+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=challenge_dag, task_id=extract_task, execution_date=20241128T111314, start_date=20241128T111316, end_date=20241128T111316
[2024-11-28T11:13:16.993+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-11-28T11:13:17.007+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
